### ISSUE TITLE
Publish output for the pipeline workflow

### ISSUE THREAD

**Issue by mjtice** [StackStorm-Exchange/stackstorm-terraform#20]
Hey guys, before I go too far with a PR are you okay if I publish the output of each task (on failure, to a dict) in the pipeline workflow?

e.g.

```
output:
  - errors: <% ctx().terraform_errors %>

vars:
  - terraform_errors:
      init: null
      select_workspace: null
      create_workspace: null
      plan: null
      apply: null
      destroy: null

... snip ...
next:
      - when: <% failed() %>
        publish:
          - terraform_errors:
              apply: <% task('apply') %>
        do: fail
```

Or is there something else you'd rather see?
