### ISSUE TITLE
Too Many Arguments Error when st2 run terraform.init plan_path

### ISSUE THREAD

**Issue by setswei** [StackStorm-Exchange/stackstorm-terraform#41]
Hello, 

I am receiving the following error when I try to use the terraform.init action in stack storm

```
id: 63be204d1ffffbbf817002b4
action.ref: terraform.init
context.user: st2admin
parameters: 
  plan_path: /opt/stackstorm/packs/DIRECTORY/
status: failed
start_timestamp: Wed, 11 Jan 2023 02:34:53 UTC
end_timestamp: Wed, 11 Jan 2023 02:34:54 UTC
result: 
  exit_code: 0
  result: null
  stderr: 'Too many command line arguments. Did you mean to use -chdir?
    '
  stdout: ''
```

The /opt/stackstorm/packs/DIRECTORY/ has all of my terraform templates in it and the action step itself is basic

```
  task2:
    action: terraform.init
    input:
      plan_path: /opt/stackstorm/packs/DIRECTORY/
      terraform_exec: terraform
```

I have confirmed that terraform is installed and all python dependencies are as well. Has anyone else experienced this error or am I missing something?

Thanks
